name: Build OnePlus 6 Kernel with KernelSU and docker

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: "true"
      CCACHE_MAXSIZE: "5G"
      CCACHE_HARDLINK: "true"
      KERNEL_DEFCONFIG: "oneplus6_KSU-docker_defconfig"
      KERNEL_CMDLINE: "ARCH=arm64 CC=clang CLANG_TRIPLE=aarch64-linux-gnu- CROSS_COMPILE=aarch64-linux-gnu- CROSS_COMPILE_ARM32=arm-linux-gnueabi- O=out LLVM=1"

    steps:
    - name: Checkout this repository
      uses: actions/checkout@v3
      with:
        ref: main
        path: repo

    - name: Checkout kernel code
      uses: actions/checkout@v3
      with:
        repository: LineageOS/android_kernel_oneplus_sdm845
        ref: lineage-20
        path: android_kernel_oneplus_sdm845

    - name: Checkout AnyKernel3 code
      uses: actions/checkout@v3
      with:
        ref: AnyKernel3
        path: AnyKernel3

    - name: Set up ccache
      uses: hendrikmuhs/ccache-action@v1.2

    - name: Install dependencies
      run: |
        sudo apt update -y
        sudo apt upgrade -y
        sudo apt install gcc-aarch64-linux-gnu -y
        sudo apt install gcc-arm-linux-gnueabi -y
        sudo apt install binutils make python3 libssl-dev build-essential bc  bison flex unzip libssl-dev ca-certificates xz-utils mkbootimg cpio device-tree-compiler git git-lfs -y

    - name: Check KernelSU code
      run: |
        cd android_kernel_oneplus_sdm845
        curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s main

    - name: Get version and commit
      run: |
        cd android_kernel_oneplus_sdm845/KernelSU
        VERSION=$(($(git rev-list --count HEAD) + 10200))
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo $VERSION

    - name: download clang and delete some AnyKernel3 code
      run: |
        wget https://github.com/llvm/llvm-project/releases/download/llvmorg-14.0.0/clang+llvm-14.0.0-x86_64-linux-gnu-ubuntu-18.04.tar.xz
        tar xf clang+llvm-14.0.0-x86_64-linux-gnu-ubuntu-18.04.tar.xz
        rm -rf AnyKernel3/.git

    - name: modify code
      run: |
        cd android_kernel_oneplus_sdm845
        git apply ../repo/diff/patch.diff
        git apply ../repo/diff/drivers.diff
        git apply ../repo/diff/selinux.diff
        cp ../repo/configs/oneplus6_KSU-docker_defconfig ./arch/arm64/configs

    - name: Submit the modified file
      run: |
        cd android_kernel_oneplus_sdm845
        git config --global user.name "aoxiang1221"
        git config --global user.email "wu13355973460@gmail.com"
        git add .
        git commit -m "update"

    - name: Build Kernel With KernelSU
      run: |
        export PATH=$(pwd)/clang+llvm-14.0.0-x86_64-linux-gnu-ubuntu-18.04/bin/:$PATH
        cd android_kernel_oneplus_sdm845
        make $KERNEL_CMDLINE $KERNEL_DEFCONFIG CC="ccache clang"
        make $KERNEL_CMDLINE CC="ccache clang" -j$(nproc --all) LLVM=1
        cp out/arch/arm64/boot/Image.gz-dtb ../AnyKernel3

    - name: Upload AnyKernel3
      uses: actions/upload-artifact@v3
      with:
        name: AnyKernel3_oneplus6_KSU-docker_${{ env.VERSION }}
        path: "AnyKernel3/*"
